spring.application.name=reactive-roots

spring.datasource.url=jdbc:mysql://0z4o2v.h.filess.io:3307/reactive_roots_settlersso?useSSL=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=never

logging.level.org.springframework.security=DEBUG